#!/bin/bash

cd /home/ethanhackney/code/http-server/tool/perf
if ! make; then
  echo "$(basename $0): make failed"
  exit 1
fi

./main.py --name "LEX_HASH" ../../main/perf/*.tab | \
  sed 's/__STRUCT__/kword/g' >hash.h
if [ $? -ne 0 ]; then
  exit 1
fi

mv hash.h ../../parse/include/
rm lib.so
