#!/bin/bash

printf 'GET /path/to/thing HTTP/1.1\r\n'  >req
printf 'Host: localhost\r\n'             >>req
printf 'User-Agent: firefox\r\n'         >>req
printf 'Accept: application/json\r\n'    >>req
printf '\r\n'                            >>req
